### ISSUE TITLE
Window type

### ISSUE THREAD

**Issue by FreddieChopin** [maxiwell/conky-seamod#1]
Hello!

In very recent version of conky I had to change:

`own_window_type = 'override',`

to:

`own_window_type = 'normal',`

The same change was done twice. Otherwise I got:

```
$ conky -c ~/.conky/seamod/conkyrc.lua 
conky: desktop window (400036) is subwindow of root window (1e6)
conky: window type - override
conky: drawing to created window (0x1800002)
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  1 (X_CreateWindow)
  Serial number of failed request:  83
  Current serial number in output stream:  87
```

**Comment by maxiwell** [comment]
Hi Freddie,

Which conky version and linux distribution?

**Comment by FreddieChopin** [comment]
conky 1.10.2 on Arch Linux. I'm using "conky-lua-nv" package from AUR.

**Comment by JPvRiel** [comment]
Same issue for me on Ubuntu Gnome 16.04.1. And `own_window_type = 'overide',` was repeated twice in the current `conkyrc.lua`.

**Comment by ire4ever1190** [comment]
Needs to be closed
