### ISSUE TITLE
Title bar

### ISSUE THREAD

**Issue by santiihoyos** [maxiwell/conky-seamod#2]
Hi, on ubuntu 16.04 i have this problem:

![captura de pantalla de 2016-05-31 12-31-45](https://cloud.githubusercontent.com/assets/10730150/15671580/be361354-272b-11e6-881a-f93305d718ef.png)

I am tried chage own_window_type normal by own_window_type desktop but dont works very well.

regards.

**Comment by maxiwell** [comment]
Hi, 

Which 'window hints' are you using? If you set override in 'window type' what happens? 
The conky didn't find the font "Ubuntu:size=11:style=normal". Try install the  'ttf-mscorefonts-installer' package.

**Comment by santiihoyos** [comment]
hi, with "override" the title bar disappear but it doesn't work later when i open a window:

![captura de pantalla de 2016-07-01 18-58-19](https://cloud.githubusercontent.com/assets/10730150/16528561/d0482d98-3fbd-11e6-92d2-0ab7c28468ae.png)

ty for the answer.
